### ISSUE TITLE
Problem creating a new item in Inventory Manager

### ISSUE THREAD

**Issue by sheilap127** [jrattanpal/InventoryManagerNP#4]
<img width="861" alt="Error popup on Item" src="https://user-images.githubusercontent.com/56122514/83240910-f884bd00-a191-11ea-8fc9-2f0958ed609a.PNG">

I would also like to remove the Spanish as we are located in the UK, is this possible?

I am working in a sandbox and can't see what Item actions are supposed to do although I have created some.  

Thank you very much for your quick response and support.

**Comment by jrattanpal** [comment]
Unfortunately, that information is not enough for me to see what is going
on.

Do you have any developers who can debug and provide more information?

If not the
Is it your sandbox? Is it possible to get a temporary login for me to check?


As for labels, those cannot be changed for now. We may do it in the future
and provide translations.  Is that a blocker? I won’t be able to change
that soon

**Comment by sheilap127** [comment]
Hi

Happy to provide a login if you can send me an email. 

Kind regards
Sheila

**Comment by jrattanpal** [comment]
Can you send it me at jrattanpal[AT]salesforce.com? (Change [AT] with @)

I will delete this comment after posting; you should receive an email with this info. Please do not reply to this email as that will store my email here.

**Comment by jrattanpal** [comment]
You should've received my email in previous comment (That I deleted)

**Comment by sheilap127** [comment]
Dear Jaswinder

Sorry, I’m not able to find it. Have sent you a linked in invitation. 

Kind regards
Sheila

**Comment by sheilap127** [comment]
![image](https://user-images.githubusercontent.com/56122514/83907118-c14b7880-a75c-11ea-9923-4f9330db0a1d.png)
