### ISSUE TITLE
Inventory Manager Not Working

### ISSUE THREAD

**Issue by EstebanJGA** [jrattanpal/InventoryManagerNP#5]
Hello!

I just installed the package and the Inventory Manager shows no items, even though they are created. MyDomain is deployed to all users and the permission set is assigned. Tried it in both sandbox and production with no success. 

![image](https://user-images.githubusercontent.com/70773158/92272346-fb88fb00-eeae-11ea-99cc-10ca9387fe15.png)

**Comment by jrattanpal** [comment]
This is strange. I created a new scratch org and it's all working. Apex debug log will be helpful but as it's managed package, it will not show up there (without Salesforce support enabling debug log for this package).

Permission is the only thing I can think of. 

Or, have you assigned a location to a user? If you don't assign a location to the user then items will not show up.

If you don't want to assign locations to a user and need that ALL "unassigned" location items will show up to ALL users, then you need to check "isEnabled" in  "Show Items in Locations without User" Custom metadata type. (Make sure you are on the latest version)

**Comment by jrattanpal** [comment]
Closing this issue for now. If you still have issue then please log it again and let me know how to reproduce it so I can debug.
