### ISSUE TITLE
Process Clarification question

### ISSUE THREAD

**Issue by djtsystems** [jrattanpal/InventoryManagerNP#6]
When I manually create an Item Action record, shouldn't it update the inventory count for related Item record?

**Comment by djtsystems** [comment]
Similarly, If I create an Item record, add a Count, shouldn't it create an Item Action record?

**Comment by djtsystems** [comment]
What I'm seeing is that there's only an Item Action record created if I use your Inventory Manager interface and only if I use the "+" or "-" buttons. When I enter a number and click Add, it doesn't create an Item Action record.

**Comment by jrattanpal** [comment]
I tested it just now  (And also reviewed the code), item actions are being logged for both actions. +/- and Add/Remove buttons.

**Comment by djtsystems** [comment]
I'm not sure you understood what I was saying. Let me explain differently.

1) Go to Item Actions
2) Create a new Item Action record
3) do NOT see inventory increased or decreased

**Comment by loesinga** [comment]
Hi all,

I seem to be having the same questions, but @djtsystems let me know if this is unrelated and I ought to start a new thread instead. 

I wish to use Inventory Manager with flows/processes that update inventory from related objects. So I thought to set up a flow/process that would create an Item Action record to update inventory when a certain event occurred. However, as @djtsystems mentions, creating an Item Action record alone does not update the related Item's inventory.

Is there a recommended method for using a flow or process to update inventory in the Inventory Manager app?

**Comment by jrattanpal** [comment]
@loesinga 

The issue mentioned above is different. 

You have it the other way around. Item Action records are created when
1) Item Action log is turned on via custom metadata type
2) Item record is created

Once you have that metadata type enabled, item action record will be automatically created when you change inventory **via Lightning Component**.

For Flow, you will have to write your own log however you want. You have to write 2 record inserts; 1 for item and 1 for item action based on the logic that you want.

**Comment by djtsystems** [comment]
My issue is actually the same as @loesinga. Ultimately, I'm trying to do the same Flow action. 

If I understand you correctly, that's not possible to do. We want the functionality to be able to create an Item Action that then updates the **current** Item records. But your solution says to create a **new** Item record and Item Action. 

Is there a roadmap to add the functionality that both @loesinga and I are seeking?

**Comment by jrattanpal** [comment]
@djtsystems There is currently no roadmap for that. The reason:

1)
This functionality of creating Item Action record came later and is optional. This is to only track who changed an inventory, when etc. It has no bearing on item, inventory etc.

I do not mean you need to create new item records. You can **update an item record inventory** and that **should add a new item action record** to keep track of that (Again, via UI only. This is not done via trigger or flow although I guess I could change that but it will still be same functionality.

2)
I am still not sure why you will want to achieve that. Updating an item (Via Lightning UI) automatically creates Item action to keep track of updates. For your solution, you can implement a flow to run on an action which does what you want; these are simple custom objects.

**Comment by djtsystems** [comment]
I understand how it currently works but the request is to add the functionality to be able to do this through a Flow. 

My reason is because I have InKind goods donations that need to be itemized in a separate custom object because the InKind opportunity is more about the total value rather than what was actually given. In the custom object, I create a record for each type of item that was donated. I then wanted a Flow to automatically update the Inventory upon creation of my custom record.

Also, I was relating my custom record to the Item Action record by sending back the Item Action number to my custom record. I was trying to create the option to "correct" inventory counts from either the custom record or the Item Action record. Sometimes a user makes a mistake with the counts and needs to correct it on these records to make sure we have an accurate audit.

**Comment by jrattanpal** [comment]
My apologies, but I don't understand. 

Those records are in custom objects. You are free to create any functionality via a Flow that can add/update records in those objects. This is a specific use case so you can build your own functionality as you see fit.

There is no blocker that stops you from building your own flows for Item objects.

**Comment by djtsystems** [comment]
Ok, never mind. I'll look into other apps to use instead.

**Comment by jrattanpal** [comment]
Sorry to hear that this app didn't fit your needs. This was built for a very specific purpose and we don't want to change the basic premise of the app.
