### ISSUE TITLE
Add this feature: Ability to assign more than one SF User to a location

### ISSUE THREAD

**Issue by djtsystems** [jrattanpal/InventoryManagerNP#7]
I get the reasoning behind why only one user is able to be assigned to a location.

But smaller nonprofits are short-handed and so some users may need to jump in to update inventory on the fly.

**Comment by jrattanpal** [comment]
For this, there is a feature that you can enable from Custom Metadata Type called "Show Items in Locations without User". When enabled, this will show inventory items for ALL users where there is no user assigned to a location. 

This will keep existing functionality (As that was the requirement) as well as resolve your use case.

**Comment by djtsystems** [comment]
ok, thanks.

**Comment by jrattanpal** [comment]
I'll close this issue for now. Please let me know if you have any questions.
